### ISSUE TITLE
Biome ID Fixer causing crashes whenever I load a modpack with it in

### ISSUE THREAD

**Issue by webwraith** [desagas/Biome-Id-Fixer#12]
Whenever I update the NTC2 modpack past the first version I downloaded (which I believe was 1.3.9 for the pack) I have to remove Biome ID Fixer as it causes every world to crash before I've joined them. This occurs in both brand new and pre-existing worlds. I'm aware that others have not had this problem, and I'm not sure what might be causing it, but when I remove Biome ID Fixer from the pack and relaunch, I am able to run the pack with no troubles.

When the program crashes, it hasn't even left the dirt texture background, or shown the little box that fills out at the bottom of the screen. I will provide the initial part of the crash log here, but link the complete crash log
```

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 5/11/22 1:23 AM
Description: mouseClicked event handler

java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_312] {}
	at java.lang.Integer.parseInt(Integer.java:592) ~[?:1.8.0_312] {}
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_312] {}
	at com.desagas.biomeidfixer.Read.importBiomeMap(Read.java:36) ~[biomeidfixer:1.16.5-1.0.1.s5] {re:classloading}
	at com.desagas.biomeidfixer.Write.getOrTryBiomeAssignment(Write.java:45) ~[biomeidfixer:1.16.5-1.0.1.s5] {re:mixin,re:classloading}
	at net.minecraft.util.registry.DynamicRegistries.handler$zlh000$registerRegistry(DynamicRegistries.java:551) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:biomeidfixer.mixins.json:MixinDynamicRegistries,pl:mixin:A}
	...


```

There is no biomeidfixer.json file in the directory structure, only a biomeidfixer.temp with the path to the world

 - Forge Version: 1.16.5-forge-36.2.34
 - Biome mods and Versions: BoP
 - Version of Biome Fixer: 1.16.5-1.0.1.s5

[crash-2022-05-11_01.23.18-client.txt](https://github.com/desagas/Biome-Id-Fixer/files/8665739/crash-2022-05-11_01.23.18-client.txt)

**Comment by desagas** [comment]
I am testing this pack right now. I will report back.

**Comment by desagas** [comment]
It seems to load just fine for me. New worlds, server worlds ... have you by any chance added any mods? Or are you updating from a previous version of the pack? Anything else?

**Comment by starcraft66** [comment]
Just experienced this on the FTB Academy 1.16 pack. The server crashed, idk why and this exact same number format exception happens on startup and prevents the server from starting.

**Comment by starcraft66** [comment]
Looks like my `world/biomeidfixer/BiomeIdFixer.json` file exists but is truncated (0 bytes) and the code does not account for this scenario at all.

**Comment by TanCY1** [comment]
I also have this issue

**Comment by Erokaution** [comment]
I also have this issue when joining a server.
The file does not appear to be downloading correctly and causes the error in OP.

**Comment by desagas** [comment]
The file does not download, it is generated when you first load in. This means that if the server you are playing on has one already generated, if it is altered in any way, you would need to download the one from the server, as directed in the wiki for BiomeIdFixer. This may cause issues, but I have no way around it.
