### ISSUE TITLE
Is a 1.18.2 port planned?

### ISSUE THREAD

**Issue by MachineRat8** [desagas/Biome-Id-Fixer#13]
I'm playing ATM7, and I want to remove a couple of mods, but doing so prevents me from being able to continue my survival world, I remembered that this is caused by an issue with biome IDs, so I was wondering, is this eventually going to be ported to 1.18.2?

**Comment by desagas** [comment]
I believe in 1.18 minecraft fixed biome issues, did they not? This mod only made existing biomes act the same ... if you remove a mod with a biome in it, that space has to be filled with another biome, which means previously generated biomes would act as what they were replaced with, but, the biome map shouldn't change, just its coloring and weather and ambiance may change. BiomeIdFixer never changed which biomes generated, it only prevent say a Jungle from behaving like a Soul Valley if a mod was removed. But, both biomes still exist in the game.

I hope you found a solution. I doubt I will port this, as I have yet to see the drastic issues BoP caused in 1.16.5 in later verions.
