### ISSUE TITLE
Crash on world build

### ISSUE THREAD

**Issue by Zygus42** [desagas/Biome-Id-Fixer#3]
Possibly to do with using TerraForged as the world builder ?

[crash-2021-01-23_21.45.35-server.txt](https://github.com/desagas/Biome-Id-Fixer/files/5860291/crash-2021-01-23_21.45.35-server.txt)

biomeidfixer-1.16.4-1.0.0.s0

**Comment by drakray** [comment]
Got the same error, no TerraForged though
https://pastebin.com/arqQwThW

**Comment by desagas** [comment]
Duplicate of https://github.com/desagas/Biome-Id-Fixer/issues/2.
