### ISSUE TITLE
Crash on Windows 11

### ISSUE THREAD

**Issue by NillerMedDild** [desagas/Biome-Id-Fixer#7]
**Describe the bug**
Crash when joining and creating worlds.

**To Reproduce**
1. Be on Windows 11
2. Join or create a world with BiomeIdFixer
3. Crash

**Expected behavior**
No crash.

**Screenshots AND BiomeIdFixer jsonFiles**
I asked the original reporter for his json, I'll edit this when he replies.

**Versions (please complete the following information):**
 - Forge Version: 1.16.5-36.2.1
 - Biome mods and Versions: BYG, BoP, Rats, etc.
 - [Biomes You Go 1.3.0 MCV: 1.16.5](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3409287) 
 - Version of Biome Fixer: [BiomeIdFixer 1.16.5-1.0.1.s4 (Forge)](https://www.curseforge.com/minecraft/mc-mods/biome-id-fixer/files/3317420)

**Additional context**
Relayed from https://github.com/NillerMedDild/Enigmatica6/issues/2930

**Comment by desagas** [comment]
Thanks, Niels, I will look into it as soon as I can. :)

**Comment by desagas** [comment]
Seems to be based on a corrupted file, as per other thread. Might be a windows update error or a Java update error, but I will continue to look into how to make this bullet proof in the future.

as I suspected, replacing the master biome file fixes the issue.
